### ISSUE TITLE
【期望】webui生成视频后提供在线预览下载功能

### ISSUE THREAD

**Issue by Ikaros-521** [harry0703/MoneyPrinterTurbo#106]
如题
临时凑合改了改 webui
```
# 在Streamlit应用中创建视频
def create_video(title: str, video_path: str):
    # 添加一个标题
    st.title(title)

    # 添加视频，从文件加载
    video_file = open(video_path, 'rb')  # 确保替换为你的视频文件名
    video_bytes = video_file.read()

    # 显示视频
    st.video(video_bytes)
```

```
logger.info("开始生成视频")

resp_json = tm.start(task_id=task_id, params=cfg)

if resp_json:
    logger.info(f"{resp_json}")
    if "videos" in resp_json:
        for video_path in resp_json["videos"]:
            create_video(task_id, video_path)
```

**Comment by harry0703** [comment]
感谢反馈

已经加了视频生成完成后，`自动打开输出文件夹` 的逻辑了，方便查看
webui里面的预览，我后面加进去

**Comment by Ikaros-521** [comment]
> 感谢反馈
> 
> 已经加了视频生成完成后，`自动打开输出文件夹` 的逻辑了，方便查看 webui里面的预览，我后面加进去

好好好 
![image](https://github.com/harry0703/MoneyPrinterTurbo/assets/40910637/046f90aa-4d6f-4f42-b5cf-8442e16108d2)

**Comment by shanghailiwei** [comment]
考虑有的场景是 服务不是部署在本地， 在远程的服务器上的话， 需要添加一个下载的url连接即可。 
app/services/task.py 最后修改为：

```python

    video_urls = [f"https://dl.yien.vip/{path.replace(utils.root_dir(), '')}" for path in final_video_paths]

    kwargs = {
        "videos": final_video_paths,
        "video_urls": video_urls,

    }
    sm.update_task(task_id, state=const.TASK_STATE_COMPLETE, progress=100, **kwargs)
    return kwargs

``` 
webui/Main.py 的最后改为。
```python
    result=tm.start(task_id=task_id, params=params)
    video_urls = result.get("video_urls", [])
    if video_urls:
        st.success("视频生成完成,请点击以下链接下载:")
        for i, url in enumerate(video_urls):
            st.markdown(f"{i+1}. [{os.path.basename(url)}]({url})")
    else:
        st.success("视频生成完成")

    open_task_folder(task_id)
    logger.info(tr("Video Generation Completed"))

```

**Comment by shanghailiwei** [comment]
当然这样的话有一个风险，就是最好是从storage目录下面的task目录通过http服务器给share出来。

我的设置里，加入一个限制，nginx除了mp4文件，其他任何类型的文件都不允许下载。 避免你的 config.toml文件泄漏。

**Comment by harry0703** [comment]
@shanghailiwei 👍

1，video_urls = [f"https://dl.yien.vip/{path.replace(utils.root_dir(), '')}" for path in final_video_paths]
这个有了，配置文件里面设置 endpoint 即可，默认是用的 http://127.0.0.1:8080

```toml
[app]
    # 当视频生成成功后，API服务提供的视频下载接入点，默认为当前服务的地址和监听端口
    # 比如 http://127.0.0.1:8080/tasks/6357f542-a4e1-46a1-b4c9-bf3bd0df5285/final-1.mp4
    # 如果你需要使用域名对外提供服务（一般会用nginx做代理），则可以设置为你的域名
    # 比如 https://xxxx.com/tasks/6357f542-a4e1-46a1-b4c9-bf3bd0df5285/final-1.mp4
    # endpoint="https://xxxx.com"

    # When the video is successfully generated, the API service provides a download endpoint for the video, defaulting to the service's current address and listening port.
    # For example, http://127.0.0.1:8080/tasks/6357f542-a4e1-46a1-b4c9-bf3bd0df5285/final-1.mp4
    # If you need to provide the service externally using a domain name (usually done with nginx as a proxy), you can set it to your domain name.
    # For example, https://xxxx.com/tasks/6357f542-a4e1-46a1-b4c9-bf3bd0df5285/final-1.mp4
    # endpoint="https://xxxx.com"
    endpoint=""
```

2，很棒，点击直接下载
