### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 815056753qqcom** [harry0703/MoneyPrinterTurbo#3]
把按顺序取三个视频，调整为随机取三个视频更好一些
random.choice(url_list)

**Comment by harry0703** [comment]
我做成一个配置项，可以按顺序，也可以随机，这样就更灵活一些

**Comment by harry0703** [comment]
@815056753qqcom 已增加配置项
```toml
[pexels]
    video_concat_mode="sequential" # "random" or "sequential"
```
