### ISSUE TITLE
下载时报错：[Errno 101] Network is unreachable, NewConnectionError

### ISSUE THREAD

**Issue by MGmint** [harry0703/MoneyPrinterTurbo#32]
错误信息：
failed to download video: https://player.vimeo.com/progressive_redirect/playback/443175492/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=56c778aaa5a722776a3a6d26201ea05cd5dfdcff6053a2948891d4d362f11792, HTTPSConnectionPool(host='player.vimeo.com', port=443): Max retries exceeded with url: /progressive_redirect/playback/443175492/rendition/1080p/file.mp4?loc=external&oauth2_token_id=1747418641&signature=56c778aaa5a722776a3a6d26201ea05cd5dfdcff6053a2948891d4d362f11792 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2086550e50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
这个必须使用魔法才可以吗？？
这个必须使用魔法才可以吗？？

**Comment by harry0703** [comment]
这个必须要用魔法
如果你有代理服务器的话，也可以设置 `pexels.proxies` 为你的代理服务器地址

```toml
[pexels]
    video_concat_mode="sequential" # "random" or "sequential"
    [pexels.proxies]
        ### Use a proxy to access the Pexels API
        ### Format: "http://<username>:<password>@<proxy>:<port>"
        ### Example: "http://user:pass@proxy:1234"
        ### Doc: https://requests.readthedocs.io/en/latest/user/advanced/#proxies
        # http = "http://10.10.1.10:3128"
        # https = "http://10.10.1.10:1080"
```
