### ISSUE TITLE
启动webui报错

### ISSUE THREAD

**Issue by KangXin4J** [harry0703/MoneyPrinterTurbo#49]
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.

**Comment by harry0703** [comment]
感谢反馈，已经优化了这个问题
请**更新代码**，然后配置文件里面设置


### RuntimeError: No ffmpeg exe could be found
通常情况下，ffmpeg 会被自动下载，并且会被自动检测到。
但是如果你的环境有问题，无法自动下载，可能会遇到如下错误：
```
RuntimeError: No ffmpeg exe could be found.
Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
```
此时你可以从 https://www.gyan.dev/ffmpeg/builds/ 下载ffmpeg，解压后，设置 `ffmpeg_path` 为你的实际安装路径即可。
```toml
[app]
    # 请根据你的实际路径设置，注意 Windows 路径分隔符为 \\
    ffmpeg_path = "C:\\Users\\harry\\Downloads\\ffmpeg.exe"
```
