### ISSUE TITLE
v1.2.3需要用户名密码登录，在哪里创建？

### ISSUE THREAD

**Issue by Uchihayht** [harry0703/MoneyPrinterTurbo#637]
### 是否已存在类似问题？

- [x] 我已搜索现有问题

### 当前行为

更新到v1.2.3版本，点击配置需要用户名和密码登录。老哥，都私有化部署了，再要求登陆账号，是不是有点多此一举了？

### 预期行为

告知在哪里创建账户密码

### 重现步骤

告知在哪里创建账户密码

### 堆栈追踪/日志

告知在哪里创建账户密码

### Python 版本

v1.2.3

### 操作系统

windows10

### MoneyPrinterTurbo 版本

v1.2.3

**Comment by harry0703** [comment]
配置文件中
```toml
[user]
username = "admin"
password = "admin"
email = "admin@example.com"
```
