### ISSUE TITLE
项目非常棒，提几个小建议哈

### ISSUE THREAD

**Issue by jerryblues** [harry0703/MoneyPrinterTurbo#8]
1. AI API key 的配置，建议可以优化一下：

- 提供一个免费的选项供体验，比如原版提供的 g4f
- 支持其他类型的 API key，比如通过 One API 项目产生的 API key

2. 建议 prompt 可以由用户手动提供，类似原版那样。这样可能可以提升文本内容丰富性。
3. 支持选择仅生成音频，或者这个可以另外启一个项目。

**Comment by jerryblues** [comment]
关于API key，还可以支持 moonshot，兼容openAI，方便国内用户使用：https://platform.moonshot.cn/

**Comment by skmoyi** [comment]
通义千问也可以支持，还不用翻墙

**Comment by harry0703** [comment]
@skmoyi 千问已经支持了
```toml
# 支持的提供商 (Supported providers):
#   openai
#   moonshot (月之暗面)
#   oneapi
#   g4f
#   azure
#   qwen (通义千问)
llm_provider="qwen" 

########## Qwen API Key
# Visit https://dashscope.console.aliyun.com/apiKey to get your API key
# Visit below links to get more details
# https://tongyi.aliyun.com/qianwen/
# https://help.aliyun.com/zh/dashscope/developer-reference/model-introduction
qwen_api_key = ""
qwen_model_name = "qwen-max" 
```
